<template>
    <div>
        <ic-flexbox>
            <ic-flexbox-item>
                导航栏
            </ic-flexbox-item>
        </ic-flexbox>
        <ic-navbar
            title="NavBar"
            leftContent="返回"
            rightContent="说明"
            leftIcon
            rightIcon
        ></ic-navbar>
    </div>
</template>